# Exported from Render on 2026-01-28T11:48:51Z
version: "1"
projects:
- name: krosspost
  environments:
  - name: Production
    services:
    - type: web
      name: krosspost
      runtime: node
      repo: https://github.com/yash-desai-naik/krosspost_shopify
      plan: free
      envVars:
      - key: SHOPIFY_WEBHOOKS_PATH
        sync: false
      - key: SHOPIFY_SCOPES
        sync: false
      - key: SHOPIFY_AUTH_CALLBACK_URL
        sync: false
      - key: META_WEBHOOK_PATH
        sync: false
      - key: APP_URL
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: LOG_LEVEL
        sync: false
      - key: META_IG_USER_ACCESS_TOKEN
        sync: false
      - key: META_IG_BUSINESS_ACCOUNT_ID
        sync: false
      - key: META_PAGE_ACCESS_TOKEN
        sync: false
      - key: META_WEBHOOK_VERIFY_TOKEN
        sync: false
      - key: META_APP_SECRET
        sync: false
      - key: META_APP_ID
        sync: false
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SHOPIFY_API_KEY
        sync: false
      - key: REDIS_URL
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: PORT
        sync: false
      - key: NODE_ENV
        sync: false
      region: singapore
      buildCommand: pnpm install --frozen-lockfile && pnpm run build
      startCommand: node dist/index.js
      domains:
      - krosspost.yashddesai.com
      autoDeployTrigger: commit
